### ISSUE TITLE
World Finals checklist

### ISSUE THREAD

**Issue by teapotd** [teapotd/algolib#157]
- [x] geometria 2D i 3D!!!!!!!!!
- [x] voronoi, delaunay, hull 3D!!!
- [ ] porządny appendix!
- [x] max-clique
- [x] wypisywanie int128
- [x] usunąć std::function
- [x] text/hashing
- [x] specjalizacje drzew przedziałowych
- [x] zmiana inicjalizerów {} na =
- [x] 64-arne drzewko
- [ ] ~~drzewka 2D?~~
- [ ] ~~trees/euler_tour_tree albo dorobić subtree queries do link cut tree~~
- [ ] upychamy do 25 stron, selekcja
